{
 "title": "FusionPBX",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "domain", "label": "Domain: ", "query": { "query": "label_values(domain)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({job=\"fusionpbx\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "FusionPBX", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Domain Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "domains_count{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(inbound_calls_per_domain_last_15s{domain=~\"$domain\",instance=\"$instance\"}) + sum(outbound_calls_per_domain_last_15s{domain=~\"$domain\",instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Call Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Outbound Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "outbound_calls_per_domain_last_15s{domain=~\"$domain\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Inbound Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "inbound_calls_per_domain_last_15s{domain=~\"$domain\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Average Call Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "avg_call_duration_per_domain_last_15s{domain=~\"$domain\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Answered Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "answered_calls_per_domain_last_15s{domain=~\"$domain\",instance=\"$instance\"}"
    }
   ]
  }
 ]
}