{
 "title": "FusionPBX",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({job=\"fusionpbx\"},instance)"
    }
   },
   {
    "name": "domain",
    "label": "Domain: ",
    "query": {
     "query": "label_values({instance=\"$instance\"},domain)"
    }
   }
  ]
 },
 "panels": [
  { "title": "FusionPBX", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Domain Count",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "domains_count{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Extension Count",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(extensions_per_domain{instance=~\"$instance\", domain=~\"$domain\"})"
    }
   ]
  },
  {
   "title": "Total Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(inbound_calls_per_domain{domain=~\"$domain\",instance=\"$instance\"}) + sum(outbound_calls_per_domain{domain=~\"$domain\",instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MOS Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "average_mos_per_domain{domain=~\"$domain\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Call Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Outbound Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "outbound_calls_per_domain{domain=~\"$domain\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Inbound Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "inbound_calls_per_domain{domain=~\"$domain\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Average Call Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "avg_call_duration_per_domain{domain=~\"$domain\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Answered Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "answered_calls_per_domain{domain=~\"$domain\",instance=\"$instance\"}"
    }
   ]
  }
 ]
}